/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.estadioArbitragem;
/**
 *
 * @author helto
 */
public class TelaDesignacaoArbitro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDesignacaoArbitro.class.getName());

    /**
     * Creates new form TelaDesignacaoArbitro
     */
    public TelaDesignacaoArbitro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDesignacaoArb = new javax.swing.JPanel();
        jLabelArbitroDesArb = new javax.swing.JLabel();
        jLabelFuncaoDesArb = new javax.swing.JLabel();
        jComboBoxArbitroDesArb = new javax.swing.JComboBox<>();
        jComboBoxFuncaoDesArb = new javax.swing.JComboBox<>();
        jButtonSalvarDesArb = new javax.swing.JButton();
        jButtonFecharDesArb = new javax.swing.JButton();
        jLabelFuncaoDesArb1 = new javax.swing.JLabel();
        jComboBoxPartidaDesArb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDesignacaoArb.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Designação Árbitro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabelArbitroDesArb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelArbitroDesArb.setText("Árbitro:");

        jLabelFuncaoDesArb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFuncaoDesArb.setText("Função:");

        jComboBoxArbitroDesArb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Árbitro 1", "Árbitro 2", "Árbitro 3", "Árbitro 4" }));

        jComboBoxFuncaoDesArb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Principal", "Assistente", "VAR", "Quarto Árbitro" }));

        jButtonSalvarDesArb.setText("Salvar");
        jButtonSalvarDesArb.addActionListener(this::jButtonSalvarDesArbActionPerformed);

        jButtonFecharDesArb.setText("Fechar");
        jButtonFecharDesArb.addActionListener(this::jButtonFecharDesArbActionPerformed);

        jLabelFuncaoDesArb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFuncaoDesArb1.setText("Partida:");

        jComboBoxPartidaDesArb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Partida 1", "Partida 2", "Partida 3", "Partida 4" }));

        javax.swing.GroupLayout jPanelDesignacaoArbLayout = new javax.swing.GroupLayout(jPanelDesignacaoArb);
        jPanelDesignacaoArb.setLayout(jPanelDesignacaoArbLayout);
        jPanelDesignacaoArbLayout.setHorizontalGroup(
            jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesignacaoArbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDesignacaoArbLayout.createSequentialGroup()
                        .addComponent(jLabelArbitroDesArb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxArbitroDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDesignacaoArbLayout.createSequentialGroup()
                        .addComponent(jLabelFuncaoDesArb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFuncaoDesArb, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanelDesignacaoArbLayout.createSequentialGroup()
                        .addComponent(jLabelFuncaoDesArb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPartidaDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDesignacaoArbLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButtonSalvarDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButtonFecharDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanelDesignacaoArbLayout.setVerticalGroup(
            jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesignacaoArbLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArbitroDesArb)
                    .addComponent(jComboBoxArbitroDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncaoDesArb)
                    .addComponent(jComboBoxFuncaoDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncaoDesArb1)
                    .addComponent(jComboBoxPartidaDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelDesignacaoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharDesArb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesignacaoArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesignacaoArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarDesArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarDesArbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarDesArbActionPerformed

    private void jButtonFecharDesArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharDesArbActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFecharDesArbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDesignacaoArbitro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharDesArb;
    private javax.swing.JButton jButtonSalvarDesArb;
    private javax.swing.JComboBox<String> jComboBoxArbitroDesArb;
    private javax.swing.JComboBox<String> jComboBoxFuncaoDesArb;
    private javax.swing.JComboBox<String> jComboBoxPartidaDesArb;
    private javax.swing.JLabel jLabelArbitroDesArb;
    private javax.swing.JLabel jLabelFuncaoDesArb;
    private javax.swing.JLabel jLabelFuncaoDesArb1;
    private javax.swing.JPanel jPanelDesignacaoArb;
    // End of variables declaration//GEN-END:variables
}
