/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.estadioArbitragem;
/**
 *
 * @author helto
 */
public class TelaCadastroEstadio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroEstadio.class.getName());

    /**
     * Creates new form TelaCadastroEstadio
     */
    public TelaCadastroEstadio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroEst = new javax.swing.JPanel();
        jLabelNomeEst = new javax.swing.JLabel();
        jLabelLocalizacaoEst = new javax.swing.JLabel();
        jLabelCapacidadeEst = new javax.swing.JLabel();
        jTextFieldNomeEst = new javax.swing.JTextField();
        jTextFieldLocalizacaoEst = new javax.swing.JTextField();
        jTextFieldCapacidadeEst = new javax.swing.JTextField();
        jButtonSalvarCadEst = new javax.swing.JButton();
        jButtonEditarCadEst = new javax.swing.JButton();
        jButtonExcluirCadEst = new javax.swing.JButton();
        jButtonFecharCadEst = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaEst = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Estádio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabelNomeEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomeEst.setText("Nome:");

        jLabelLocalizacaoEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLocalizacaoEst.setText("Localização:");

        jLabelCapacidadeEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCapacidadeEst.setText("Capacidade:");

        jTextFieldLocalizacaoEst.addActionListener(this::jTextFieldLocalizacaoEstActionPerformed);

        jButtonSalvarCadEst.setText("Salvar");
        jButtonSalvarCadEst.addActionListener(this::jButtonSalvarCadEstActionPerformed);

        jButtonEditarCadEst.setText("Editar");
        jButtonEditarCadEst.addActionListener(this::jButtonEditarCadEstActionPerformed);

        jButtonExcluirCadEst.setText("Excluir");
        jButtonExcluirCadEst.addActionListener(this::jButtonExcluirCadEstActionPerformed);

        jButtonFecharCadEst.setText("Fechar");
        jButtonFecharCadEst.addActionListener(this::jButtonFecharCadEstActionPerformed);

        javax.swing.GroupLayout jPanelCadastroEstLayout = new javax.swing.GroupLayout(jPanelCadastroEst);
        jPanelCadastroEst.setLayout(jPanelCadastroEstLayout);
        jPanelCadastroEstLayout.setHorizontalGroup(
            jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelLocalizacaoEst)
                        .addComponent(jLabelCapacidadeEst))
                    .addComponent(jLabelNomeEst))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldNomeEst, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCapacidadeEst)
                        .addComponent(jTextFieldLocalizacaoEst))
                    .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                        .addComponent(jButtonSalvarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFecharCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanelCadastroEstLayout.setVerticalGroup(
            jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeEst))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroEstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldNomeEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalizacaoEst)
                    .addComponent(jTextFieldLocalizacaoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCapacidadeEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCapacidadeEst))
                .addGap(53, 53, 53)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTableListaEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Localização", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaEst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelCadastroEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLocalizacaoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLocalizacaoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLocalizacaoEstActionPerformed

    private void jButtonSalvarCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarCadEstActionPerformed

    private void jButtonEditarCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCadEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarCadEstActionPerformed

    private void jButtonExcluirCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirCadEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirCadEstActionPerformed

    private void jButtonFecharCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCadEstActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharCadEstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroEstadio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarCadEst;
    private javax.swing.JButton jButtonExcluirCadEst;
    private javax.swing.JButton jButtonFecharCadEst;
    private javax.swing.JButton jButtonSalvarCadEst;
    private javax.swing.JLabel jLabelCapacidadeEst;
    private javax.swing.JLabel jLabelLocalizacaoEst;
    private javax.swing.JLabel jLabelNomeEst;
    private javax.swing.JPanel jPanelCadastroEst;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaEst;
    private javax.swing.JTextField jTextFieldCapacidadeEst;
    private javax.swing.JTextField jTextFieldLocalizacaoEst;
    private javax.swing.JTextField jTextFieldNomeEst;
    // End of variables declaration//GEN-END:variables
}
