/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUISelecaoJogador;

import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jp67a
 */
public class ConsultaSelecaoJogador extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaSelecaoJogador
     */
    public ConsultaSelecaoJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelOpcao = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelPosicao = new javax.swing.JLabel();
        botaoConsultar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jRadioButtonSelecao = new javax.swing.JRadioButton();
        jRadioButtonJogador = new javax.swing.JRadioButton();
        comboBoxStatus = new javax.swing.JComboBox<>();
        comboBoxPosicao = new javax.swing.JComboBox<>();
        txtInputGrupo = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultaTable = new javax.swing.JTable();

        labelOpcao.setText("Selecione uma opção:");

        labelGrupo.setText("Grupo:");

        labelStatus.setText("Status:");

        labelPosicao.setText("Posição:");

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(this::botaoConsultarActionPerformed);

        botaoEditar.setText("Editar");

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(this::botaoExcluirActionPerformed);

        buttonGroup1.add(jRadioButtonSelecao);
        jRadioButtonSelecao.setText("Seleção");
        jRadioButtonSelecao.addActionListener(this::jRadioButtonSelecaoActionPerformed);

        buttonGroup1.add(jRadioButtonJogador);
        jRadioButtonJogador.setText("Jogador");
        jRadioButtonJogador.addActionListener(this::jRadioButtonJogadorActionPerformed);

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "LESIONADO", "SUSPENSO" }));

        comboBoxPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOLEIRO", "ZAGUEIRO", "LATERAL", "VOLANTE", "PONTA", "CENTROAVANTE", "RESERVA" }));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(this::botaoVoltarActionPerformed);

        consultaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(consultaTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelOpcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonSelecao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonJogador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPosicao)
                                .addGap(2, 2, 2)
                                .addComponent(comboBoxPosicao, 0, 158, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOpcao)
                    .addComponent(jRadioButtonSelecao)
                    .addComponent(jRadioButtonJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrupo)
                    .addComponent(labelStatus)
                    .addComponent(labelPosicao)
                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInputGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditar)
                    .addComponent(botaoConsultar)
                    .addComponent(botaoExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja prosseguir?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso.");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void jRadioButtonSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSelecaoActionPerformed
        // TODO add your handling code here:
        txtInputGrupo.setEnabled(true);
        comboBoxPosicao.setEnabled(false);
        comboBoxStatus.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonSelecaoActionPerformed

    private void jRadioButtonJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJogadorActionPerformed
        // TODO add your handling code here:
        txtInputGrupo.setEnabled(false);
        comboBoxPosicao.setEnabled(true);
        comboBoxStatus.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonJogadorActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        // TODO add your handling code here:
        consultaTable.clearSelection();
        if(txtInputGrupo.isEnabled() && comboBoxStatus.isEnabled() && comboBoxPosicao.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção.", "Erro!", JOptionPane.OK_OPTION);
        }
        else{
            String[] colunas = null;
            if (txtInputGrupo.isEnabled() && !comboBoxStatus.isEnabled() && !comboBoxPosicao.isEnabled()) {
                colunas = new String[] {"País", "Grupo", "Técnico"};
            }
            else if (!txtInputGrupo.isEnabled() && comboBoxStatus.isEnabled() && comboBoxPosicao.isEnabled()){
                colunas = new String[] {"Nome", "Status", "Número", "Seleção", "Posição"};
            }
            consultaTable.setModel(new DefaultTableModel(null, colunas));
        }

    }//GEN-LAST:event_botaoConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxPosicao;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JTable consultaTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonJogador;
    private javax.swing.JRadioButton jRadioButtonSelecao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelOpcao;
    private javax.swing.JLabel labelPosicao;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField txtInputGrupo;
    // End of variables declaration//GEN-END:variables
}
