/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.estadioArbitragem.telas;

import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.example.estadioArbitragem.Estadio;
import org.example.estadioArbitragem.GerenciadorEstadioJSON;
import org.example.estadioArbitragem.OrganizaEstadio;

/**
 *
 * @author helto
 */
public class TelaCadastroEstadio extends javax.swing.JFrame {
    
    public boolean editar = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroEstadio.class.getName());

    /**
     * Creates new form TelaCadastroEstadio
     */
    public TelaCadastroEstadio() {
        initComponents();
        estadoInicial();
        DefaultTableModel modelo = (DefaultTableModel) tabelaEstadios.getModel();
        tabelaEstadios.setRowSorter(new TableRowSorter(modelo));
        
        GerenciadorEstadioJSON gejson = new GerenciadorEstadioJSON();
        List<Estadio> listaSalva = gejson.carregarEstadio();
        
        for (Estadio est : listaSalva){
            modelo.addRow(new Object[]{est.getNome(), est.getLocalizacao(), est.getCapacidade()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroEst = new javax.swing.JPanel();
        jLabelNomeEst = new javax.swing.JLabel();
        jLabelLocalizacaoEst = new javax.swing.JLabel();
        jLabelCapacidadeEst = new javax.swing.JLabel();
        txtNomeEst = new javax.swing.JTextField();
        txtLocalizacaoEst = new javax.swing.JTextField();
        txtCapacidadeEst = new javax.swing.JTextField();
        btnSalvarCadEst = new javax.swing.JButton();
        btnEditarCadEst = new javax.swing.JButton();
        btnExcluirCadEst = new javax.swing.JButton();
        btnFecharCadEst = new javax.swing.JButton();
        btnNovoCadEst = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEstadios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Estádio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabelNomeEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomeEst.setText("Nome:");

        jLabelLocalizacaoEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLocalizacaoEst.setText("Localização:");

        jLabelCapacidadeEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCapacidadeEst.setText("Capacidade:");

        txtLocalizacaoEst.addActionListener(this::txtLocalizacaoEstActionPerformed);

        btnSalvarCadEst.setText("Salvar");
        btnSalvarCadEst.addActionListener(this::btnSalvarCadEstActionPerformed);

        btnEditarCadEst.setText("Editar");
        btnEditarCadEst.addActionListener(this::btnEditarCadEstActionPerformed);

        btnExcluirCadEst.setText("Excluir");
        btnExcluirCadEst.addActionListener(this::btnExcluirCadEstActionPerformed);

        btnFecharCadEst.setText("Fechar");
        btnFecharCadEst.addActionListener(this::btnFecharCadEstActionPerformed);

        btnNovoCadEst.setText("Novo");
        btnNovoCadEst.addActionListener(this::btnNovoCadEstActionPerformed);

        javax.swing.GroupLayout jPanelCadastroEstLayout = new javax.swing.GroupLayout(jPanelCadastroEst);
        jPanelCadastroEst.setLayout(jPanelCadastroEstLayout);
        jPanelCadastroEstLayout.setHorizontalGroup(
            jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelLocalizacaoEst)
                                .addComponent(jLabelCapacidadeEst))
                            .addComponent(jLabelNomeEst))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeEst, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidadeEst)
                            .addComponent(txtLocalizacaoEst)))
                    .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnNovoCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFecharCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanelCadastroEstLayout.setVerticalGroup(
            jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroEstLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeEst))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroEstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNomeEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalizacaoEst)
                    .addComponent(txtLocalizacaoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidadeEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCapacidadeEst))
                .addGap(53, 53, 53)
                .addGroup(jPanelCadastroEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecharCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoCadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        tabelaEstadios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Localização", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEstadios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEstadiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaEstadios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelCadastroEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoInicial(){
        
        btnSalvarCadEst.setEnabled(false);
        btnEditarCadEst.setEnabled(false);
        btnExcluirCadEst.setEnabled(false);
        btnNovoCadEst.setEnabled(true);
        
        txtNomeEst.setEnabled(false);
        txtCapacidadeEst.setEnabled(false);
        txtLocalizacaoEst.setEnabled(false);
        
        limparCampos();
        editar = false;
        tabelaEstadios.clearSelection();
        
    }
    
    private void txtLocalizacaoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizacaoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacaoEstActionPerformed

    private void btnSalvarCadEstActionPerformed(java.awt.event.ActionEvent evt) {                                                
        GerenciadorEstadioJSON gerenciador = new GerenciadorEstadioJSON();
        List<Estadio> listaEstadio = gerenciador.carregarEstadio();
        
        for(Estadio est : listaEstadio){
            if(txtNomeEst.getText().equals(est.getNome())){
                JOptionPane.showMessageDialog(rootPane, "Estadio já cadastrado.");
                return;
            }
        }


        if(txtNomeEst.getText().equals("")
                || txtLocalizacaoEst.getText().equals("")
                || txtCapacidadeEst.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Verifique os campos em branco!");
            
        } else{
            try{
                String nome = txtNomeEst.getText();
                String localizacao = txtLocalizacaoEst.getText();
                int capacidade = Integer.parseInt(txtCapacidadeEst.getText());
                
                OrganizaEstadio organiza = new OrganizaEstadio();

                DefaultTableModel dtmTabela = (DefaultTableModel)tabelaEstadios.getModel();
                
                if(editar == false){             
                    organiza.CadastrarNovoEstadio(nome, localizacao, capacidade, dtmTabela);  
                    JOptionPane.showMessageDialog(rootPane, "Estádio " + nome + " cadastrado com sucesso!");  
                    
                } else {
                    int linhaVisual = tabelaEstadios.getSelectedRow();
                    if (linhaVisual == -1){
                        JOptionPane.showMessageDialog(rootPane, "Selecione um estádio na tabela para editar.");
                        return;
                    }
                    int linhaReal = tabelaEstadios.convertRowIndexToModel(linhaVisual);
                    organiza.EditarEstadio(WIDTH, linhaReal, nome, localizacao, capacidade, dtmTabela);
                    JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso!");
                    
                }

                estadoInicial();
                
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "A capacidade deve conter apenas números inteiros!", "Erro de Formatação", JOptionPane.ERROR_MESSAGE);
            } catch(IllegalArgumentException e){
                JOptionPane.showMessageDialog(rootPane, "Erro de validação!");
            }
            
        }
        
                                                       
    }                                               

    private void limparCampos(){
        txtNomeEst.setText("");
        txtLocalizacaoEst.setText("");
        txtCapacidadeEst.setText("");
    }
    private void btnEditarCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadEstActionPerformed
        
        if(tabelaEstadios.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Nenhuma linha selecionada!");
        } else {
            editar = true;
            habilitarCampos();
            btnEditarCadEst.setEnabled(false);
            btnExcluirCadEst.setEnabled(false);
            btnNovoCadEst.setEnabled(false);
            btnSalvarCadEst.setEnabled(true);
            
        }
    }//GEN-LAST:event_btnEditarCadEstActionPerformed

    private void btnExcluirCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadEstActionPerformed
        int linhaSelecionada = tabelaEstadios.getSelectedRow();
        
        if(tabelaEstadios.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Nenhuma linha selecionada!");
            return;
        } else {
            
            int op = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir esse estadio?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);

            if(op == JOptionPane.YES_OPTION){
                try{
                    int indexReal = tabelaEstadios.convertRowIndexToModel(linhaSelecionada);
                    DefaultTableModel dtmTabela = (DefaultTableModel) tabelaEstadios.getModel();
                    OrganizaEstadio organiza = new OrganizaEstadio();
                    organiza.ExcluirEstadio(linhaSelecionada, indexReal, dtmTabela);
                    
                    JOptionPane.showMessageDialog(rootPane, "Estadio excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    estadoInicial();
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, "Erro ao excluir o estadio: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
                


            }
                
        }
    }//GEN-LAST:event_btnExcluirCadEstActionPerformed

    private void btnFecharCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCadEstActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharCadEstActionPerformed

    private void tabelaEstadiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEstadiosMouseClicked
       // estadoInicial();
        
        btnEditarCadEst.setEnabled(true);
        btnExcluirCadEst.setEnabled(true);
        btnNovoCadEst.setEnabled(true);
        
        int linhaSelecionada = tabelaEstadios.getSelectedRow();
        if (linhaSelecionada != -1){
            txtNomeEst.setText(tabelaEstadios.getValueAt(linhaSelecionada, 0 ).toString());
            txtLocalizacaoEst.setText(tabelaEstadios.getValueAt(linhaSelecionada, 1 ).toString());
            txtCapacidadeEst.setText(tabelaEstadios.getValueAt(linhaSelecionada, 2 ).toString());
        }
        
    }//GEN-LAST:event_tabelaEstadiosMouseClicked

    private void btnNovoCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadEstActionPerformed
        estadoInicial();
        habilitarCampos();
        btnSalvarCadEst.setEnabled(true);    
        btnNovoCadEst.setEnabled(false);
        
    }//GEN-LAST:event_btnNovoCadEstActionPerformed
    
    private void habilitarCampos(){
        txtNomeEst.setEnabled(true);
        txtLocalizacaoEst.setEnabled(true);
        txtCapacidadeEst.setEnabled(true);
    }
    
//    private void atualizarArquivoJSON(){
//        DefaultTableModel modelo = (DefaultTableModel) tabelaEstadios.getModel();
//        java.util.List<Estadio> listaParaSalvar = new java.util.ArrayList<>();
//        
//        for(int i = 0; i < modelo.getRowCount(); i++){
//            String nome = modelo.getValueAt(i, 0).toString();
//            String localizacao = modelo.getValueAt(i, 1).toString();
//            int capacidade = Integer.parseInt(modelo.getValueAt(i, 2).toString());
//            
//            listaParaSalvar.add(new Estadio(nome, localizacao, capacidade));
//            
//        }
//        
//        GerenciadorEstadioJSON gejson = new GerenciadorEstadioJSON();
//        gejson.salvarEstadios(listaParaSalvar);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroEstadio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCadEst;
    private javax.swing.JButton btnExcluirCadEst;
    private javax.swing.JButton btnFecharCadEst;
    private javax.swing.JButton btnNovoCadEst;
    private javax.swing.JButton btnSalvarCadEst;
    private javax.swing.JLabel jLabelCapacidadeEst;
    private javax.swing.JLabel jLabelLocalizacaoEst;
    private javax.swing.JLabel jLabelNomeEst;
    private javax.swing.JPanel jPanelCadastroEst;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEstadios;
    private javax.swing.JTextField txtCapacidadeEst;
    private javax.swing.JTextField txtLocalizacaoEst;
    private javax.swing.JTextField txtNomeEst;
    // End of variables declaration//GEN-END:variables
}
