/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.estadioArbitragem.telas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.example.administracao.Usuario;
import org.example.administracao.UsuarioLogado;
import org.example.estadioArbitragem.Arbitro;
import org.example.partidas.*;

/**
 *
 * @author helto
 */
public class TelaPartidasDesignadas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPartidasDesignadas.class.getName());
    private UsuarioLogado sessaoAtual;

    /**
     * Creates new form TelaPartidasDesignadas
     * @param sessaoAtual
     */
    
    public TelaPartidasDesignadas(UsuarioLogado sessaoAtual) {
        this.sessaoAtual = sessaoAtual;
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaPartidas.getModel();
        
        try{
            listarJogosDoArbitroLogado(modelo, this.sessaoAtual);
        } catch(Exception e){
            System.err.println("Erro ao carregar listagem automática: " + e.getMessage());
        } 
    }
    
    public void listarJogosDoArbitroLogado(DefaultTableModel modeloTabela, UsuarioLogado sessaoAtual) throws Exception{
        modeloTabela.setRowCount(0);
        
        Usuario usuario = sessaoAtual.getUsuario();
           
        String nomeArbitroLogado = usuario.getNome();
        
        try{
            List<PartidaCopa> todasAsPartidas = new ArrayList<>();
            todasAsPartidas.addAll(new FaseGrupos().listarPartidas());
            todasAsPartidas.addAll(new OitavasFinal().listarPartidas());
            todasAsPartidas.addAll(new QuartasFinal().listarPartidas());
            todasAsPartidas.addAll(new SemiFinal().listarPartidas());
            todasAsPartidas.addAll(new Final().listarPartidas());
            
            for(PartidaCopa partida : todasAsPartidas){
                String arbitroDaPartida = partida.getArbitro();
                
                if(arbitroDaPartida != null && arbitroDaPartida.contains(nomeArbitroLogado)){
                    String fase = partida.getFase();
                    String confronto = partida.getSelecao1() + " x " + partida.getSelecao2();
                    String data = partida.getData();
                    String estadio = partida.getEstadio();
                    modeloTabela.addRow(new Object[]{fase, confronto, data, estadio});
                }
            }
        } catch(Exception e){
            System.err.println("Erro ao carregar os jogos " + e.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPartidas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partidas Designadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Segue abaixo suas partidas designadas:");

        tabelaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fase", "Jogo", "Data", "Estadio"
            }
        ));
        tabelaPartidas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaPartidasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPartidas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaPartidasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaPartidasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaPartidasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new TelaPartidasDesignadas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPartidas;
    // End of variables declaration//GEN-END:variables
}
